language: node_js
dist: bionic
notifications:
  email:
    recipients:
    - kschwarz@hexonet.net
    on_success: never
    on_failure: always
node_js:
  - '12'
  - '11'
  - '10'
  - '9'
  - '8'
# Trigger a push build on master and dependabot branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^dependabot.*$/
before_install:
  - npm prune
install:
  - travis_retry npm i
  - travis_retry pip install -r requirements.txt --user
before_script:
  - npm run lint
script:
  - npm run test --silent >/dev/null
  - "./scripts/pep8check.sh"
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npx semantic-release
